### ISSUE TITLE
image-service-relation-changed raise EOFError: Missing required data: rabbitmq_password

### ISSUE THREAD

**Issue by vmorris** [openstack-charmers/charm-nova-compute-proxy#2]
Please let me know if there's a more appropriate place to open issues with this charm, thanks!

After adding rabbitmq-server, glance, and neutron-api relations, the proxy charm ends with ERROR juju.worker.uniter.operation hook "image-service-relation-changed" failed: exit status 1

It seems to be failing to get the rabbitmq admin password?

```
unit-nova-compute-proxy-2: 01:30:37 INFO unit.nova-compute-proxy/2.juju-log image-service:41: Making dir /var/lib/charm/nova-compute-proxy/etc/nova root:root 555
unit-nova-compute-proxy-2: 01:30:37 INFO unit.nova-compute-proxy/2.juju-log image-service:41: Registered config file: /var/lib/charm/nova-compute-proxy/etc/nova/nova.conf
unit-nova-compute-proxy-2: 01:30:37 INFO unit.nova-compute-proxy/2.juju-log image-service:41: Making dir /var/lib/charm/nova-compute-proxy/etc/nova root:root 555
unit-nova-compute-proxy-2: 01:30:37 INFO unit.nova-compute-proxy/2.juju-log image-service:41: Making dir /var/lib/charm/nova-compute-proxy/etc/nova root:root 555
unit-nova-compute-proxy-2: 01:30:37 INFO unit.nova-compute-proxy/2.juju-log image-service:41: Making dir /var/lib/charm/nova-compute-proxy/etc/nova root:root 555
unit-nova-compute-proxy-2: 01:30:37 INFO unit.nova-compute-proxy/2.juju-log image-service:41: Making dir /var/lib/charm/nova-compute-proxy/etc/nova root:root 555
unit-nova-compute-proxy-2: 01:30:37 INFO unit.nova-compute-proxy/2.juju-log image-service:41: Making dir /var/lib/charm/nova-compute-proxy/etc/nova root:root 555
unit-nova-compute-proxy-2: 01:30:37 INFO unit.nova-compute-proxy/2.juju-log image-service:41: Making dir /var/lib/charm/nova-compute-proxy/etc/nova root:root 555
unit-nova-compute-proxy-2: 01:30:38 DEBUG unit.nova-compute-proxy/2.juju-log image-service:41: Generating template context for amqp
unit-nova-compute-proxy-2: 01:30:38 INFO unit.nova-compute-proxy/2.juju-log image-service:41: Missing required data: rabbitmq_password
unit-nova-compute-proxy-2: 01:30:38 DEBUG unit.nova-compute-proxy/2.juju-log image-service:41: Generating template context for image-service.
unit-nova-compute-proxy-2: 01:30:39 DEBUG unit.nova-compute-proxy/2.juju-log image-service:41: 0 section(s) found
unit-nova-compute-proxy-2: 01:30:39 DEBUG unit.nova-compute-proxy/2.juju-log image-service:41: Generating template context for amqp
unit-nova-compute-proxy-2: 01:30:39 INFO unit.nova-compute-proxy/2.juju-log image-service:41: Missing required data: rabbitmq_password
unit-nova-compute-proxy-2: 01:30:39 DEBUG unit.nova-compute-proxy/2.juju-log image-service:41: Generating template context for image-service.
unit-nova-compute-proxy-2: 01:30:39 DEBUG unit.nova-compute-proxy/2.juju-log image-service:41: 0 section(s) found
unit-nova-compute-proxy-2: 01:30:39 INFO unit.nova-compute-proxy/2.juju-log image-service:41: Creating choice loader with dirs: [['templates/mitaka'], ['templates/'], ['/var/lib/juju/agents/unit-nova-compute-proxy-2/charm/hooks/charmhelpers/contrib/openstack/templates']]
unit-nova-compute-proxy-2: 01:30:39 INFO unit.nova-compute-proxy/2.juju-log image-service:41: Loaded template from templates/mitaka/nova.conf
unit-nova-compute-proxy-2: 01:30:40 INFO unit.nova-compute-proxy/2.juju-log image-service:41: Rendering from template: nova.conf
unit-nova-compute-proxy-2: 01:30:40 INFO unit.nova-compute-proxy/2.juju-log image-service:41: Wrote template /var/lib/charm/nova-compute-proxy/etc/nova/nova.conf.
unit-nova-compute-proxy-2: 01:30:40 INFO unit.nova-compute-proxy/2.image-service-relation-changed /usr/lib/python2.7/getpass.py:83: GetPassWarning: Can not control echo on the terminal.
unit-nova-compute-proxy-2: 01:30:40 INFO unit.nova-compute-proxy/2.image-service-relation-changed   passwd = fallback_getpass(prompt, stream)
unit-nova-compute-proxy-2: 01:30:40 INFO unit.nova-compute-proxy/2.image-service-relation-changed Warning: Password input may be echoed.
unit-nova-compute-proxy-2: 01:30:40 INFO unit.nova-compute-proxy/2.image-service-relation-changed [10.20.95.79] Login password for 'root': [10.20.95.79] Executing task 'copy_file_as_root'
unit-nova-compute-proxy-2: 01:30:40 INFO unit.nova-compute-proxy/2.image-service-relation-changed Traceback (most recent call last):
unit-nova-compute-proxy-2: 01:30:40 INFO unit.nova-compute-proxy/2.image-service-relation-changed   File "/var/lib/juju/agents/unit-nova-compute-proxy-2/charm/hooks/image-service-relation-changed", line 135, in <module>
unit-nova-compute-proxy-2: 01:30:40 INFO unit.nova-compute-proxy/2.image-service-relation-changed     hooks.execute(sys.argv)
unit-nova-compute-proxy-2: 01:30:40 INFO unit.nova-compute-proxy/2.image-service-relation-changed   File "/var/lib/juju/agents/unit-nova-compute-proxy-2/charm/hooks/charmhelpers/core/hookenv.py", line 715, in execute
unit-nova-compute-proxy-2: 01:30:40 INFO unit.nova-compute-proxy/2.image-service-relation-changed     self._hooks[hook_name]()
unit-nova-compute-proxy-2: 01:30:40 INFO unit.nova-compute-proxy/2.image-service-relation-changed   File "/var/lib/juju/agents/unit-nova-compute-proxy-2/charm/hooks/nova_compute_proxy.py", line 174, in wrapped_f
unit-nova-compute-proxy-2: 01:30:40 INFO unit.nova-compute-proxy/2.image-service-relation-changed     f(*args)
unit-nova-compute-proxy-2: 01:30:40 INFO unit.nova-compute-proxy/2.image-service-relation-changed   File "/var/lib/juju/agents/unit-nova-compute-proxy-2/charm/hooks/image-service-relation-changed", line 94, in image_service_changed
unit-nova-compute-proxy-2: 01:30:40 INFO unit.nova-compute-proxy/2.image-service-relation-changed     proxy.commit()
unit-nova-compute-proxy-2: 01:30:40 INFO unit.nova-compute-proxy/2.image-service-relation-changed   File "/var/lib/juju/agents/unit-nova-compute-proxy-2/charm/hooks/nova_compute_proxy.py", line 150, in commit
unit-nova-compute-proxy-2: 01:30:40 INFO unit.nova-compute-proxy/2.image-service-relation-changed     self.copy_file(f)
unit-nova-compute-proxy-2: 01:30:40 INFO unit.nova-compute-proxy/2.image-service-relation-changed   File "/var/lib/juju/agents/unit-nova-compute-proxy-2/charm/hooks/nova_compute_proxy.py", line 123, in copy_file
unit-nova-compute-proxy-2: 01:30:40 INFO unit.nova-compute-proxy/2.image-service-relation-changed     target)
unit-nova-compute-proxy-2: 01:30:40 INFO unit.nova-compute-proxy/2.image-service-relation-changed   File "/usr/lib/python2.7/dist-packages/fabric/tasks.py", line 387, in execute
unit-nova-compute-proxy-2: 01:30:40 INFO unit.nova-compute-proxy/2.image-service-relation-changed     multiprocessing
unit-nova-compute-proxy-2: 01:30:40 INFO unit.nova-compute-proxy/2.image-service-relation-changed   File "/usr/lib/python2.7/dist-packages/fabric/tasks.py", line 277, in _execute
unit-nova-compute-proxy-2: 01:30:40 INFO unit.nova-compute-proxy/2.image-service-relation-changed     return task.run(*args, **kwargs)
unit-nova-compute-proxy-2: 01:30:40 INFO unit.nova-compute-proxy/2.image-service-relation-changed   File "/usr/lib/python2.7/dist-packages/fabric/tasks.py", line 174, in run
unit-nova-compute-proxy-2: 01:30:40 INFO unit.nova-compute-proxy/2.image-service-relation-changed     return self.wrapped(*args, **kwargs)
unit-nova-compute-proxy-2: 01:30:40 INFO unit.nova-compute-proxy/2.image-service-relation-changed   File "/var/lib/juju/agents/unit-nova-compute-proxy-2/charm/hooks/fabfile.py", line 39, in copy_file_as_root
unit-nova-compute-proxy-2: 01:30:40 INFO unit.nova-compute-proxy/2.image-service-relation-changed     put(src, dest, use_sudo=True)
unit-nova-compute-proxy-2: 01:30:40 INFO unit.nova-compute-proxy/2.image-service-relation-changed   File "/usr/lib/python2.7/dist-packages/fabric/network.py", line 649, in host_prompting_wrapper
unit-nova-compute-proxy-2: 01:30:40 INFO unit.nova-compute-proxy/2.image-service-relation-changed     return func(*args, **kwargs)
unit-nova-compute-proxy-2: 01:30:40 INFO unit.nova-compute-proxy/2.image-service-relation-changed   File "/usr/lib/python2.7/dist-packages/fabric/operations.py", line 347, in put
unit-nova-compute-proxy-2: 01:30:40 INFO unit.nova-compute-proxy/2.image-service-relation-changed     ftp = SFTP(env.host_string)
unit-nova-compute-proxy-2: 01:30:40 INFO unit.nova-compute-proxy/2.image-service-relation-changed   File "/usr/lib/python2.7/dist-packages/fabric/sftp.py", line 33, in __init__
unit-nova-compute-proxy-2: 01:30:40 INFO unit.nova-compute-proxy/2.image-service-relation-changed     self.ftp = connections[host_string].open_sftp()
unit-nova-compute-proxy-2: 01:30:40 INFO unit.nova-compute-proxy/2.image-service-relation-changed   File "/usr/lib/python2.7/dist-packages/fabric/network.py", line 159, in __getitem__
unit-nova-compute-proxy-2: 01:30:40 INFO unit.nova-compute-proxy/2.image-service-relation-changed     self.connect(key)
unit-nova-compute-proxy-2: 01:30:40 INFO unit.nova-compute-proxy/2.image-service-relation-changed   File "/usr/lib/python2.7/dist-packages/fabric/network.py", line 151, in connect
unit-nova-compute-proxy-2: 01:30:40 INFO unit.nova-compute-proxy/2.image-service-relation-changed     user, host, port, cache=self, seek_gateway=seek_gateway)
unit-nova-compute-proxy-2: 01:30:40 INFO unit.nova-compute-proxy/2.image-service-relation-changed   File "/usr/lib/python2.7/dist-packages/fabric/network.py", line 531, in connect
unit-nova-compute-proxy-2: 01:30:40 INFO unit.nova-compute-proxy/2.image-service-relation-changed     password = prompt_for_password(text)
unit-nova-compute-proxy-2: 01:30:40 INFO unit.nova-compute-proxy/2.image-service-relation-changed   File "/usr/lib/python2.7/dist-packages/fabric/network.py", line 614, in prompt_for_password
unit-nova-compute-proxy-2: 01:30:40 INFO unit.nova-compute-proxy/2.image-service-relation-changed     new_password = _password_prompt(password_prompt, stream)
unit-nova-compute-proxy-2: 01:30:40 INFO unit.nova-compute-proxy/2.image-service-relation-changed   File "/usr/lib/python2.7/dist-packages/fabric/network.py", line 586, in _password_prompt
unit-nova-compute-proxy-2: 01:30:40 INFO unit.nova-compute-proxy/2.image-service-relation-changed     return getpass.getpass(prompt.encode('ascii', 'ignore'), stream)
unit-nova-compute-proxy-2: 01:30:40 INFO unit.nova-compute-proxy/2.image-service-relation-changed   File "/usr/lib/python2.7/getpass.py", line 83, in unix_getpass
unit-nova-compute-proxy-2: 01:30:40 INFO unit.nova-compute-proxy/2.image-service-relation-changed     passwd = fallback_getpass(prompt, stream)
unit-nova-compute-proxy-2: 01:30:40 INFO unit.nova-compute-proxy/2.image-service-relation-changed   File "/usr/lib/python2.7/getpass.py", line 118, in fallback_getpass
unit-nova-compute-proxy-2: 01:30:40 INFO unit.nova-compute-proxy/2.image-service-relation-changed     return _raw_input(prompt, stream)
unit-nova-compute-proxy-2: 01:30:40 INFO unit.nova-compute-proxy/2.image-service-relation-changed   File "/usr/lib/python2.7/getpass.py", line 135, in _raw_input
unit-nova-compute-proxy-2: 01:30:40 INFO unit.nova-compute-proxy/2.image-service-relation-changed     raise EOFError
unit-nova-compute-proxy-2: 01:30:40 INFO unit.nova-compute-proxy/2.image-service-relation-changed EOFError
unit-nova-compute-proxy-2: 01:30:40 ERROR juju.worker.uniter.operation hook "image-service-relation-changed" failed: exit status 1
```

**Comment by javacruft** [comment]
This looks like a problem with the key setup between the proxy and the remote hosts its trying to manage; the charm relies on password-less SSH.

**Comment by vmorris** [comment]
@javacruft I ran into the password-less SSH problem directly and was getting hung up there until I carefully read the doc and saw that the private key needed to be placed in the files directory of the charm. Once I did that and redeployed the charm, that particular problem passed and the charm deployed, only to block awaiting the relations to rabbitmq-server, glance, and neutron (I assume this i the neutron-api service). After creating these relations, the charm debug log failed with the above.

I can see that none of the config files have been altered.... so I believe you are correct, the charm is not able to access the remove KVM host.

Looking at the access logs on the host, I notice the following message repeated:
sshd[18223]: Connection closed by 10.20.95.69 [preauth]

I'll try to get more detailed messages, but I have confirmed that the ssh key is installed and password-less access is working for a manual connection!

**Comment by vmorris** [comment]
Yes, debugging the hook, I find the following:

**Comment by vmorris** [comment]
No, still having a problem here... Any advice?

```
root@juju-0cf3d1-2-lxd-1:/var/lib/juju/agents/unit-nova-compute-proxy-2/charm# chmod 400 files/id_rsa 
root@juju-0cf3d1-2-lxd-1:/var/lib/juju/agents/unit-nova-compute-proxy-2/charm# ls -la files/id_rsa 
-r-------- 1 root root 1679 Nov  1 04:55 files/id_rsa
root@juju-0cf3d1-2-lxd-1:/var/lib/juju/agents/unit-nova-compute-proxy-2/charm# hooks/image-service-relation-changed 
[10.20.95.79] Executing task 'copy_file_as_root'
[10.20.95.79] Login password for 'root': ^c
```

I see the public key go out, but the method was disabled for some reason...


```
root@juju-0cf3d1-2-lxd-1:/var/lib/juju/agents/unit-nova-compute-proxy-2/charm# ssh -vvv -o StrictHostKeyChecking=no -i files/id_rsa root@10.20.95.79
OpenSSH_7.2p2 Ubuntu-4ubuntu2.1, OpenSSL 1.0.2g  1 Mar 2016
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug2: resolving "10.20.95.79" port 22
debug2: ssh_connect_direct: needpriv 0
debug1: Connecting to 10.20.95.79 [10.20.95.79] port 22.
debug1: Connection established.
debug1: permanently_set_uid: 0/0
debug1: key_load_public: No such file or directory
debug1: identity file files/id_rsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file files/id_rsa-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.1
debug1: Remote protocol version 2.0, remote software version OpenSSH_6.6.1
debug1: match: OpenSSH_6.6.1 pat OpenSSH_6.6.1* compat 0x04000000
debug2: fd 3 setting O_NONBLOCK
debug1: Authenticating to 10.20.95.79:22 as 'root'
debug3: hostkeys_foreach: reading file "/root/.ssh/known_hosts"
debug3: record_hostkey: found key type ECDSA in file /root/.ssh/known_hosts:1
debug3: load_hostkeys: loaded 1 keys from 10.20.95.79
debug3: order_hostkeyalgs: prefer hostkeyalgs: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
debug3: send packet: type 20
debug1: SSH2_MSG_KEXINIT sent
debug3: receive packet: type 20
debug1: SSH2_MSG_KEXINIT received
debug2: local client KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,ext-info-c
debug2: host key algorithms: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-ed25519,rsa-sha2-512,rsa-sha2-256,ssh-rsa
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,aes192-cbc,aes256-cbc,3des-cbc
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,aes192-cbc,aes256-cbc,3des-cbc
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none,zlib@openssh.com,zlib
debug2: compression stoc: none,zlib@openssh.com,zlib
debug2: languages ctos: 
debug2: languages stoc: 
debug2: first_kex_follows 0 
debug2: reserved 0 
debug2: peer server KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
debug2: host key algorithms: ssh-rsa,ecdsa-sha2-nistp256,ssh-ed25519
debug2: ciphers ctos: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
debug2: ciphers stoc: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
debug2: MACs ctos: hmac-md5-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-ripemd160-etm@openssh.com,hmac-sha1-96-etm@openssh.com,hmac-md5-96-etm@openssh.com,hmac-md5,hmac-sha1,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
debug2: MACs stoc: hmac-md5-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-ripemd160-etm@openssh.com,hmac-sha1-96-etm@openssh.com,hmac-md5-96-etm@openssh.com,hmac-md5,hmac-sha1,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
debug2: compression ctos: none,zlib@openssh.com
debug2: compression stoc: none,zlib@openssh.com
debug2: languages ctos: 
debug2: languages stoc: 
debug2: first_kex_follows 0 
debug2: reserved 0 
debug1: kex: algorithm: curve25519-sha256@libssh.org
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug3: send packet: type 30
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug3: receive packet: type 31
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:mM3BiU5Sc/jA1SH4KwVT3S93Ya4bPjtnVIFSkPnCajw
debug3: hostkeys_foreach: reading file "/root/.ssh/known_hosts"
debug3: record_hostkey: found key type ECDSA in file /root/.ssh/known_hosts:1
debug3: load_hostkeys: loaded 1 keys from 10.20.95.79
debug1: Host '10.20.95.79' is known and matches the ECDSA host key.
debug1: Found key in /root/.ssh/known_hosts:1
debug3: send packet: type 21
debug2: set_newkeys: mode 1
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug3: receive packet: type 21
debug2: set_newkeys: mode 0
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS received
debug2: key: files/id_rsa ((nil)), explicit
debug3: send packet: type 5
debug3: receive packet: type 6
debug2: service_accept: ssh-userauth
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug3: send packet: type 50
debug3: receive packet: type 51
debug1: Authentications that can continue: publickey,gssapi-keyex,gssapi-with-mic,password
debug3: start over, passed a different list publickey,gssapi-keyex,gssapi-with-mic,password
debug3: preferred gssapi-keyex,gssapi-with-mic,publickey,keyboard-interactive,password
debug3: authmethod_lookup gssapi-keyex
debug3: remaining preferred: gssapi-with-mic,publickey,keyboard-interactive,password
debug3: authmethod_is_enabled gssapi-keyex
debug1: Next authentication method: gssapi-keyex
debug1: No valid Key exchange context
debug2: we did not send a packet, disable method
debug3: authmethod_lookup gssapi-with-mic
debug3: remaining preferred: publickey,keyboard-interactive,password
debug3: authmethod_is_enabled gssapi-with-mic
debug1: Next authentication method: gssapi-with-mic
debug1: Unspecified GSS failure.  Minor code may provide more information
No Kerberos credentials available

debug1: Unspecified GSS failure.  Minor code may provide more information
No Kerberos credentials available

debug1: Unspecified GSS failure.  Minor code may provide more information


debug1: Unspecified GSS failure.  Minor code may provide more information
No Kerberos credentials available

debug2: we did not send a packet, disable method
debug3: authmethod_lookup publickey
debug3: remaining preferred: keyboard-interactive,password
debug3: authmethod_is_enabled publickey
debug1: Next authentication method: publickey
debug1: Trying private key: files/id_rsa
debug3: sign_and_send_pubkey: RSA SHA256:Ev061GqkwzZSTKDFnG5wIMk7vU5qxXxEoCEsF9VJuXM
debug3: send packet: type 50
debug2: we sent a publickey packet, wait for reply
debug3: receive packet: type 51
debug1: Authentications that can continue: publickey,gssapi-keyex,gssapi-with-mic,password
debug2: we did not send a packet, disable method
debug3: authmethod_lookup password
debug3: remaining preferred: ,password
debug3: authmethod_is_enabled password
debug1: Next authentication method: password
root@10.20.95.79's password: 

```

**Comment by vmorris** [comment]
Closing this and deferring until I can try out the charm from the charm store instead.
